<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="1" failures="0" hostname="7e3f09c0dc3a" name="pytest" skipped="0" tests="1" time="1.804" timestamp="2020-08-21T13:24:40.115827"><testcase classname="" file="tests/test_api.py" name="tests.test_api" time="0.000"><error message="collection failure">tests/test_api.py:3: in &lt;module&gt;
    from s3_io.s3io_api import create_app
s3_io/s3io_api.py:13: in &lt;module&gt;
    from s3_io.create_url_to_filesystem_task import process
s3_io/create_url_to_filesystem_task.py:21: in &lt;module&gt;
    from s3_io.s3io_tasks import swarm_to_remote
s3_io/s3io_tasks.py:13: in &lt;module&gt;
    from s3_io.s3io_tools import SwarmS3Client, SwarmIo
s3_io/s3io_tools.py:28: in &lt;module&gt;
    config = ConfigParser()
/opt/venv/lib/python3.7/site-packages/viaa/configuration.py:76: in __init__
    self.cfg = self._parse_config(config_file)
/opt/venv/lib/python3.7/site-packages/viaa/configuration.py:85: in _parse_config
    cfg: dict = yaml.load(ymlfile, Loader=yaml_loader)
/opt/venv/lib/python3.7/site-packages/yaml/__init__.py:114: in load
    return loader.get_single_data()
/opt/venv/lib/python3.7/site-packages/yaml/constructor.py:51: in get_single_data
    return self.construct_document(node)
/opt/venv/lib/python3.7/site-packages/yaml/constructor.py:60: in construct_document
    for dummy in generator:
/opt/venv/lib/python3.7/site-packages/yaml/constructor.py:413: in construct_yaml_map
    value = self.construct_mapping(node)
/opt/venv/lib/python3.7/site-packages/yaml/constructor.py:218: in construct_mapping
    return super().construct_mapping(node, deep=deep)
/opt/venv/lib/python3.7/site-packages/yaml/constructor.py:143: in construct_mapping
    value = self.construct_object(value_node, deep=deep)
/opt/venv/lib/python3.7/site-packages/yaml/constructor.py:100: in construct_object
    data = constructor(self, node)
/opt/venv/lib/python3.7/site-packages/viaa/configuration.py:45: in from_yaml
    return cls._interpolate_env_vars(match, value)
/opt/venv/lib/python3.7/site-packages/viaa/configuration.py:56: in _interpolate_env_vars
    raise KeyError(msg) from None
E   KeyError: &apos;Config requires environment variable &quot;REMOTECURL_PRIV_KEY_PATH&quot; which is not set&apos;</error></testcase></testsuite></testsuites>